### ISSUE TITLE
I have a requirement to change camelcase to snake_case properties. Is that possible?

### ISSUE THREAD

**Issue by rolfwessels** [thiagobustamante/typescript-rest-swagger#113]
Currently the output is as follows

```
properties:
            version:
                type: string
            serviceStartDate:
                type: string

```
I need it to be 

```
properties:
            version:
                type: string
            service_start_date:
                type: string
```

I know I can rename the properties but I would like to automate this if possible. 
Something like  `swaggerConfig.json`

```
...
  "swagger": {
    "outputFormat": "openapi_3",
    "propertyNameTransformer": "toSnakeCase",
}
```
Does this feature exist? Or if you point me to the right place I can have a look at implementing something like this.
