### ISSUE TITLE
Trouble generating additionalProperties

### ISSUE THREAD

**Issue by tnrich** [thiagobustamante/typescript-rest-swagger#121]
Hey @thiagobustamante 

I'm trying to generate swagger docs for some typescript that looks like: 
```ts

export interface DesignJson {
  assemblyMethod: { [key: string]: AssemblyMethod };
  ...etc
}


export interface AssemblyMethod {
  id: string;
  name: string;
}
```

However, when it gets made into the swagger.yml file, it looks like this:
```yml
    DesignJson:
        description: ""
        properties:
            assemblyMethod:
                type: object
                properties: {}
                description: ""
```

Ideally it would look more like: 
```yml
    DesignJson:
        description: ""
        properties:
            assemblyMethod:
                type: object
                properties: {}
                description: ""
                additionalProperties:
                    type: object
                    properties:
                        id:
                            type: string
                        name:
                            type: string
```

As per swagger specs
![image](https://user-images.githubusercontent.com/2730609/84189876-d3723300-aa4a-11ea-90d7-db0150d20c2f.png)

https://swagger.io/docs/specification/data-models/dictionaries/

I see this code in typescript-rest-swagger, which I assume should be finding those additional properties: 
```ts
function getModelTypeAdditionalProperties(node: UsableDeclaration) {
    if (node.kind === ts.SyntaxKind.InterfaceDeclaration) {
        const interfaceDeclaration = node as ts.InterfaceDeclaration;
        return interfaceDeclaration.members
            .filter(member => member.kind === ts.SyntaxKind.IndexSignature)
            .map((member: any) => {
                const indexSignatureDeclaration = member as ts.IndexSignatureDeclaration;

                const indexType = resolveType(indexSignatureDeclaration.parameters[0].type as ts.TypeNode);
                if (indexType.typeName !== 'string') {
                    throw new Error(`Only string indexers are supported. Found ${indexType.typeName}.`);
                }

                return {
                    description: '',
                    name: '',
                    required: true,
                    type: resolveType(indexSignatureDeclaration.type as ts.TypeNode)
                };
            });
    }

    return undefined;
}
```

but it must not be working 100%

Could you possibly take a look into this and let me know if I'm on the right track? Seems like the logic is there but it is just not detecting my TS interface as having additionalProperties. 

Thanks!
Thomas
