### ISSUE TITLE
Authorization header not getting pass under API

### ISSUE THREAD

**Issue by Gautam2010** [thiagobustamante/typescript-rest-swagger#131]
I have got option to add token as per below image
![image](https://user-images.githubusercontent.com/29875175/98678665-ee8ff880-2384-11eb-820b-86044f7c6df2.png)

and my yml file looks like this
 version: 0.0.1
  ```
securityDefinitions:
    bearer:
      type: "apiKey"
      name: "Authorization"
      in: "header"

```
When I request the API after adding token it doesn't pass token in header.
![image](https://user-images.githubusercontent.com/29875175/98678952-4dee0880-2385-11eb-99ca-1ea4bdbff574.png)

Am I missing any configuration?
